<?php

return [
    'core' => [
        '' => ['page' => 'home', 'permissions' => []],
        'anasayfa' => ['page' => 'home', 'permissions' => []],
        'admin-anasayfa' => ['page' => 'admin-home', 'permissions' => []],
        'yetkisiz-erisim' => ['page' => 'authorize', 'permissions' => []],
        'bakim-modu' => ['page' => 'under-maintance', 'permissions' => []],
    ],
    'persons' => [
        'personeller' => ['page' => 'persons/list', 'permissions' => []],
        'personel-ekle' => ['page' => 'persons/manage', 'permissions' => []],
        'personel/ekle' => ['page' => 'persons/manage', 'permissions' => []],
        'personel-duzenle' => ['page' => 'persons/manage', 'permissions' => [], 'encrypted_id' => true],
        'personel/duzenle' => ['page' => 'persons/manage', 'permissions' => [], 'encrypted_id' => true],
        'personel-ekstresi' => ['page' => 'persons/statement', 'permissions' => [], 'encrypted_id' => true],
        'personel/ekstre' => ['page' => 'persons/statement', 'permissions' => [], 'encrypted_id' => true],
        'personel-icra-dosyalari' => ['page' => 'persons/icra-list', 'permissions' => []],
        'personel-avans-talepleri' => ['page' => 'persons/advance_requests', 'permissions' => []],
        'personel-ice-aktar' => ['page' => 'persons/xls/person-load', 'permissions' => []],
        'personel-pdf' => ['page' => 'persons/to-pdf', 'permissions' => []],
        'personel-excel' => ['page' => 'persons/to-xls', 'permissions' => []],
        'icra-excel' => ['page' => 'persons/icra-export-xls', 'permissions' => []],
    ],
    'puantaj' => [
        'puantaj' => ['page' => 'puantaj/list', 'permissions' => []],
    ],
    'payroll' => [
        'bordro' => ['page' => 'payroll/list', 'permissions' => []],
        'bordro-hesapla' => ['page' => 'payroll/bordro', 'permissions' => []],
        'bordro-yazdir' => ['page' => 'raporlar/bordro-yazdir', 'permissions' => []],
        'bordro/yazdir' => ['page' => 'raporlar/bordro-yazdir', 'permissions' => []],
        'hesap-pusulasi' => ['page' => 'payroll/pay-slip', 'permissions' => [], 'encrypted_id' => true],
        'odeme-ice-aktar' => ['page' => 'payroll/xls/payment-load-from-xls', 'permissions' => []],
    ],
    'izin' => [
        'izin-talepleri' => ['page' => 'izin/list', 'permissions' => []],
        'izin-hakedisleri' => ['page' => 'izin/hakedis', 'permissions' => []],
    ],
    'projects' => [
        'projeler' => ['page' => 'projects/list', 'permissions' => []],
        'proje-ekle' => ['page' => 'projects/manage', 'permissions' => []],
        'proje/ekle' => ['page' => 'projects/manage', 'permissions' => []],
        'proje-duzenle' => ['page' => 'projects/manage', 'permissions' => [], 'encrypted_id' => true],
        'proje/duzenle' => ['page' => 'projects/manage', 'permissions' => [], 'encrypted_id' => true],
    ],
    'companies' => [
        'firmalar' => ['page' => 'companies/list', 'permissions' => []],
        'firma-ekle' => ['page' => 'companies/manage', 'permissions' => []],
        'firma/ekle' => ['page' => 'companies/manage', 'permissions' => []],
        'firma-duzenle' => ['page' => 'companies/manage', 'permissions' => [], 'encrypted_id' => true],
        'firma/duzenle' => ['page' => 'companies/manage', 'permissions' => [], 'encrypted_id' => true],
    ],
    'mycompany' => [
        'firmalarim' => ['page' => 'mycompany/list', 'permissions' => []],
        'firmam-ekle' => ['page' => 'mycompany/manage', 'permissions' => []],
        'firmam/ekle' => ['page' => 'mycompany/manage', 'permissions' => []],
        'firmam-duzenle' => ['page' => 'mycompany/manage', 'permissions' => [], 'encrypted_id' => true],
        'firmam/duzenle' => ['page' => 'mycompany/manage', 'permissions' => [], 'encrypted_id' => true],
    ],
    'financial' => [
        'kasalar' => ['page' => 'financial/case/list', 'permissions' => []],
        'kasa-ekle' => ['page' => 'financial/case/manage', 'permissions' => []],
        'kasa/ekle' => ['page' => 'financial/case/manage', 'permissions' => []],
        'kasa-duzenle' => ['page' => 'financial/case/manage', 'permissions' => [], 'encrypted_id' => true],
        'kasa/duzenle' => ['page' => 'financial/case/manage', 'permissions' => [], 'encrypted_id' => true],
        'gelir-gider-islemleri' => ['page' => 'financial/transactions/list', 'permissions' => []],
    ],
    'cari' => [
        'cariler' => ['page' => 'cari/list', 'permissions' => []],
        'cari-hareketleri' => ['page' => 'cari/movements', 'permissions' => []],
    ],
    'raporlar' => [
        'raporlar' => ['page' => 'raporlar/list', 'permissions' => []],
    ],
    'avans_talepleri' => [
        'avans-talepleri' => ['page' => 'avans-talepleri/list', 'permissions' => []],
    ],
    'missions' => [
        'gorevler' => ['page' => 'gorevler/list', 'permissions' => []],
        'gorev-listesi' => ['page' => 'missions/list', 'permissions' => []],
        'yeni-gorev' => ['page' => 'missions/manage', 'permissions' => []],
        'gorev-ekle' => ['page' => 'missions/manage', 'permissions' => []],
        'gorev/ekle' => ['page' => 'missions/manage', 'permissions' => []],
        'gorev-duzenle' => ['page' => 'missions/manage', 'permissions' => [], 'encrypted_id' => true],
        'gorev/duzenle' => ['page' => 'missions/manage', 'permissions' => [], 'encrypted_id' => true],
        'gorev-surecleri' => ['page' => 'missions/process/list', 'permissions' => []],
        'gorev-surec-ekle' => ['page' => 'missions/process/manage', 'permissions' => []],
        'gorev-surec-duzenle' => ['page' => 'missions/process/manage', 'permissions' => [], 'encrypted_id' => true],
        'gorev-basliklari' => ['page' => 'missions/headers/list', 'permissions' => []],
        'gorev-baslik-ekle' => ['page' => 'missions/headers/manage', 'permissions' => []],
        'gorev-baslik-duzenle' => ['page' => 'missions/headers/manage', 'permissions' => [], 'encrypted_id' => true],
    ],
    'todos' => [
        'yapilacaklar' => ['page' => 'todos/list', 'permissions' => []],
        'yapilacak-ekle' => ['page' => 'todos/manage', 'permissions' => []],
        'yapilacak/ekle' => ['page' => 'todos/manage', 'permissions' => []],
        'yapilacak-duzenle' => ['page' => 'todos/manage', 'permissions' => [], 'encrypted_id' => true],
        'yapilacak/duzenle' => ['page' => 'todos/manage', 'permissions' => [], 'encrypted_id' => true],
    ],
    'users' => [
        'kullanicilar' => ['page' => 'users/list', 'permissions' => []],
        'kullanici-ekle' => ['page' => 'users/manage', 'permissions' => []],
        'kullanici/ekle' => ['page' => 'users/manage', 'permissions' => []],
        'kullanici-duzenle' => ['page' => 'users/manage', 'permissions' => [], 'encrypted_id' => true],
        'kullanici/duzenle' => ['page' => 'users/manage', 'permissions' => [], 'encrypted_id' => true],
        'roller' => ['page' => 'users/roles/list', 'permissions' => []],
        'rol-ekle' => ['page' => 'users/roles/manage', 'permissions' => []],
        'rol/ekle' => ['page' => 'users/roles/manage', 'permissions' => []],
        'rol-duzenle' => ['page' => 'users/roles/manage', 'permissions' => [], 'encrypted_id' => true],
        'rol/duzenle' => ['page' => 'users/roles/manage', 'permissions' => [], 'encrypted_id' => true],
        'rol-yetkileri' => ['page' => 'users/auths/auths', 'permissions' => []],
    ],
    'defines' => [
        'gelir-gider-tanimlari' => ['page' => 'defines/incexp/list', 'permissions' => []],
        'gelir-gider-tanim-ekle' => ['page' => 'defines/incexp/manage', 'permissions' => []],
        'gelir-gider-tanim-duzenle' => ['page' => 'defines/incexp/manage', 'permissions' => [], 'encrypted_id' => true],
        'is-grubu-tanimlari' => ['page' => 'defines/job-groups/list', 'permissions' => []],
        'is-grubu-tanim-ekle' => ['page' => 'defines/job-groups/manage', 'permissions' => []],
        'is-grubu-tanim-duzenle' => ['page' => 'defines/job-groups/manage', 'permissions' => [], 'encrypted_id' => true],
        'proje-durumu-tanimlari' => ['page' => 'defines/project-status/list', 'permissions' => []],
        'proje-durumu-ekle' => ['page' => 'defines/project-status/manage', 'permissions' => []],
        'proje-durumu-duzenle' => ['page' => 'defines/project-status/manage', 'permissions' => [], 'encrypted_id' => true],
        'resmi-tatil-tanimlari' => ['page' => 'defines/national-holidays/list', 'permissions' => []],
        'resmi-tatil-ekle' => ['page' => 'defines/national-holidays/manage', 'permissions' => []],
        'resmi-tatil-duzenle' => ['page' => 'defines/national-holidays/manage', 'permissions' => [], 'encrypted_id' => true],
        'puantaj-turu-tanimlari' => ['page' => 'defines/timesheet-types/list', 'permissions' => []],
        'puantaj-turu-ekle' => ['page' => 'defines/timesheet-types/manage', 'permissions' => []],
        'puantaj-turu-duzenle' => ['page' => 'defines/timesheet-types/manage', 'permissions' => [], 'encrypted_id' => true],
        'icra-daireleri' => ['page' => 'defines/icra-daireleri/list', 'permissions' => []],
        'hizmet-basliklari' => ['page' => 'defines/service-head/list', 'permissions' => []],
    ],
    'products' => [
        'urunler' => ['page' => 'products/list', 'permissions' => []],
        'urun-ekle' => ['page' => 'products/manage', 'permissions' => []],
        'urun/ekle' => ['page' => 'products/manage', 'permissions' => []],
        'urun-duzenle' => ['page' => 'products/manage', 'permissions' => [], 'encrypted_id' => true],
        'urun/duzenle' => ['page' => 'products/manage', 'permissions' => [], 'encrypted_id' => true],
    ],
    'kvkk' => [
        'kvkk' => ['page' => 'kvkk/index', 'permissions' => []],
        'kvkk-ihlalleri' => ['page' => 'kvkk/ihlaller', 'permissions' => []],
        'kvkk-talepleri' => ['page' => 'kvkk/talepler', 'permissions' => []],
    ],
    'administration' => [
        'abonelikler' => ['page' => 'abonelik-islemleri/list', 'permissions' => []],
        'abonelik-paketleri' => ['page' => 'abonelik-islemleri/paketler', 'permissions' => []],
        'paket-modulleri' => ['page' => 'abonelik-islemleri/paket-moduller', 'permissions' => []],
        'satin-alma-islemleri' => ['page' => 'abonelik-islemleri/satin-alma-islemleri', 'permissions' => []],
        'sistem-aktiviteleri' => ['page' => 'activities/index', 'permissions' => []],
        'duyurular' => ['page' => 'duyurular/list', 'permissions' => []],
        'bildirimler' => ['page' => 'bildirimler/push', 'permissions' => []],
        'mail-islemleri' => ['page' => 'mail-islemleri/index', 'permissions' => []],
        'destek-talepleri' => ['page' => 'supports/tickets', 'permissions' => []],
        'destek-yonetimi' => ['page' => 'supports/admin-tickets', 'permissions' => []],
        'destek/detay' => ['page' => 'supports/ticket-view', 'permissions' => [], 'encrypted_id' => true],
        'destek/yonetim-detay' => ['page' => 'supports/admin-ticket-view', 'permissions' => [], 'encrypted_id' => true],
        'gorus-oneri' => ['page' => 'feedback/send', 'permissions' => []],
        'ayarlar' => ['page' => 'settings/manage', 'permissions' => []],
    ],
];
